JARVIS = "jarvis"
HELP = "help"
HELLO = ["hello", "hi"]
THANK = "thank"
WHAT = "what"
WHEN = "when"
GOOGLE = "google"
CANCEL = "cancel"
WIKI = "wiki"
MAN = "man"
SHOW = ["show", "post"]
ME = "me"
MEME = ["meme", "memes"]
PORN = ["porn", "porns"]
PLEASE = "please"
WILL = ["will", "am", "can", "is", "are", "would", "do", "did"]
MANY = ["how many", "what quantity", "what number", "number"]
